### ISSUE TITLE
Can't install iGraphMatch

### ISSUE THREAD

**Issue by jesusdaniel** [dpmcsuss/iGraphMatch#15]
After trying to install via devtools, I get the following error:

```
Error: package or namespace load failed for ‘iGraphMatch’ in namespaceExport(ns, exports):
 undefined exports: get_perm, graph_match_IsoRank, graph_match_Umeyama
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/iGraphMatch’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/iGraphMatch’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/1j/1ft72mkd3cngwzhc1rs3l37m0000gs/T//RtmpTxFFkn/file1055e5f46d59/iGraphMatch_0.0.0.9000.tar.gz’ had non-zero exit status
```

**Comment by ZihuanQiao** [comment]
Hi, you should have no problem installing the `master` branch now. But we recommend installing the `dev` branch at this moment since it's more stable and involves more functionalities. Similarly, you can install the `dev` branch by running 
``` r
# install.packages("devtools")
devtools::install_github("dpmcsuss/iGraphMatch", ref = "dev")
```
in the console.

**Comment by jesusdaniel** [comment]
Thanks! I was able to install it now!

**Comment by ZihuanQiao** [comment]
Thanks for your feedbacks. We are working on fixing the `dev` branch and will let you know sooner or later. Your problem of using `graph_match_FW` function in the `master` branch is caused by some updates to the package but you should be able to use it now.

**Comment by Lujia4170** [comment]
Hi, you should have no problem installing the dev branch now.
