### ISSUE TITLE
Warning: @title/description requires a value

### ISSUE THREAD

**Issue by ZihuanQiao** [dpmcsuss/iGraphMatch#5]
1: Warning: @title [graph_match_methods.R#1]: requires a value
2: Warning: @description [graph_match_methods.R#1]: requires a value
3: Warning: @title [graph_match_methods.R#1]: requires a value
4: Warning: @description [graph_match_methods.R#1]: requires a value

Reference: https://github.com/klutometis/roxygen/issues/480

**Comment by dpmcsuss** [comment]
Fixed with commit 5767c7406cc507852028fb39b20fa987d3872b5f
