### ISSUE TITLE
cannot find "check_soft_seeds" function

### ISSUE THREAD

**Issue by fei111** [dpmcsuss/iGraphMatch#8]
I tried to run the example of "rds_sinkhorn_start" but it does not find the "check_soft_seeds" function. The information is as following:

rds_sinkhorn_start(nns=5, soft_seeds=as.data.frame(matrix(c(2,4,2,3),nrow=2)), distribution = "rnorm")
Error in rds_sinkhorn_start(nns = 5, soft_seeds = as.data.frame(matrix(c(2,  : 
  could not find function "check_soft_seeds"

What I have tried: library(GraphMatch). check the R code in the package. I don't find the "check_soft_seeds" function code. Could you help me about this?

**Comment by ZihuanQiao** [comment]
Thank you for the comment. I used an old version function which was not included in the package which caused this error.  I think now the function should be fine.
